language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
    directories:
      - $HOME/.composer/cache

before_script:
  - curl --remote-name http://get.sensiolabs.org/php-cs-fixer.phar
  - apt-get update -qq
  - apt-get install -yqq git
  - git clone https://github.com/novius-os/core.git 2a1f532 --depth 1
  - pwd
  - ls -la
  - php -v
  - php php-cs-fixer.phar -V

script: 
  - php php-cs-fixer.phar fix core/ -vv --diff --config-file ./.php_cs
