language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
    directories:
      - $HOME/.composer/cache

before_script:
  - composer install
  - curl -O http://get.sensiolabs.org/php-cs-fixer.phar

script: 
  - php php-cs-fixer.phar -V
  - php php-cs-fixer.phar fix . --dry-run --diff -vvv

