language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:                                                                                                                                                                                                                               
  - date
  - ls -la /usr/local/
  - which phantomjs

script: 
  - phantomjs --version
