language: go

go:
  - 1.7

sudo: required

before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.6/elasticsearch-2.4.6.deb
  - sudo dpkg -i --force-confnew elasticsearch-2.4.6.deb
  - sudo service elasticsearch start
  - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1; done

install:
  - echo "bypass default install"
  
script:
  - echo OK
