language: php

php:
  - 5.4
  - 5.6
  - 7.0

before_script:                                                                                                                                                                                                                               
  - date
  - ls -la
  - sudo sh -c 'echo "127.0.0.1 novius-os" >> /etc/hosts'
  - cat /etc/hosts

script: 
  - ping -c 3 127.0.0.1
