language: go

go:
  - 1.7

before_install:
  - apt-cache search elasticsearch
  - apt-cache show elasticsearch
  - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1; done

install:
  - echo "bypass default install"
  
script:
  - echo OK
