language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

sudo: false

before_script:                                                                                                                                                                                                                               
  - date
  - ls -la
  - pwd
  - id
  - printenv

script: 
  - php -v
